name: Validate and Check Sync

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  schedule:
    # Run weekly on Sundays at 6 AM UTC
    - cron: '0 6 * * 0'

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Validate YAML structure
      run: python scripts/validate.py
      
    - name: Check if generated files are up to date
      run: |
        # Generate all files
        python scripts/generate.py
        
        # Check if any files changed
        if [ -n "$(git status --porcelain)" ]; then
          echo "❌ Generated files are out of date. Please run 'make generate' and commit the changes."
          echo ""
          echo "Changed files:"
          git status --porcelain
          exit 1
        else
          echo "✅ All generated files are up to date!"
        fi
        
    - name: Check URL accessibility (weekly)
      if: github.event_name == 'schedule'
      run: python scripts/validate.py --check-urls